import type { PresentationTheme } from './types';

// ==================== PRESENTATION THEMES ====================

export const THEMES: PresentationTheme[] = [
  {
    id: 'modern-dark',
    name: 'Современная тёмная',
    nameEn: 'Modern Dark',
    primaryColor: '#8B5CF6',
    secondaryColor: '#06B6D4',
    accentColor: '#F59E0B',
    backgroundColor: '#0F172A',
    surfaceColor: '#1E293B',
    textColor: '#F8FAFC',
    textMuted: '#94A3B8',
    fontFamily: 'Inter, system-ui, sans-serif',
    headingFont: 'Inter, system-ui, sans-serif',
    gradient: 'from-violet-600 via-purple-600 to-cyan-500',
    borderRadius: '1rem',
    shadow: '0 25px 50px -12px rgba(0, 0, 0, 0.5)',
  },
  {
    id: 'modern-light',
    name: 'Современная светлая',
    nameEn: 'Modern Light',
    primaryColor: '#6366F1',
    secondaryColor: '#8B5CF6',
    accentColor: '#F97316',
    backgroundColor: '#FFFFFF',
    surfaceColor: '#F8FAFC',
    textColor: '#0F172A',
    textMuted: '#64748B',
    fontFamily: 'Inter, system-ui, sans-serif',
    headingFont: 'Inter, system-ui, sans-serif',
    borderRadius: '1rem',
    shadow: '0 25px 50px -12px rgba(0, 0, 0, 0.15)',
  },
  // Градиентные
  {
    id: 'gradient-sunset',
    name: 'Закат',
    nameEn: 'Sunset',
    primaryColor: '#F97316',
    secondaryColor: '#EC4899',
    accentColor: '#FBBF24',
    backgroundColor: '#1F2937',
    surfaceColor: '#374151',
    textColor: '#FFFFFF',
    textMuted: '#D1D5DB',
    fontFamily: 'Inter, system-ui, sans-serif',
    headingFont: 'Playfair Display, serif',
    gradient: 'from-orange-500 via-pink-500 to-purple-600',
    borderRadius: '1.5rem',
    shadow: '0 25px 50px -12px rgba(249, 115, 22, 0.3)',
  },
  {
    id: 'gradient-aurora',
    name: 'Северное сияние',
    nameEn: 'Aurora',
    primaryColor: '#22D3EE',
    secondaryColor: '#A855F7',
    accentColor: '#34D399',
    backgroundColor: '#0A0A1B',
    surfaceColor: '#1A1A2E',
    textColor: '#F0FDFA',
    textMuted: '#5EEAD4',
    fontFamily: 'Inter, system-ui, sans-serif',
    headingFont: 'Space Grotesk, sans-serif',
    gradient: 'from-cyan-400 via-purple-500 to-pink-500',
    borderRadius: '2rem',
    shadow: '0 25px 50px -12px rgba(34, 211, 238, 0.3)',
  },
  {
    id: 'gradient-ocean',
    name: 'Глубокий океан',
    nameEn: 'Deep Ocean',
    primaryColor: '#0EA5E9',
    secondaryColor: '#6366F1',
    accentColor: '#38BDF8',
    backgroundColor: '#0C1222',
    surfaceColor: '#162032',
    textColor: '#E0F2FE',
    textMuted: '#7DD3FC',
    fontFamily: 'Inter, system-ui, sans-serif',
    headingFont: 'Montserrat, sans-serif',
    gradient: 'from-blue-600 via-cyan-500 to-teal-400',
    borderRadius: '1rem',
    shadow: '0 25px 50px -12px rgba(14, 165, 233, 0.3)',
  },
  // Природа
  {
    id: 'nature-forest',
    name: 'Лесная',
    nameEn: 'Forest',
    primaryColor: '#059669',
    secondaryColor: '#84CC16',
    accentColor: '#34D399',
    backgroundColor: '#022C22',
    surfaceColor: '#064E3B',
    textColor: '#ECFDF5',
    textMuted: '#6EE7B7',
    fontFamily: 'Inter, system-ui, sans-serif',
    headingFont: 'Lora, serif',
    gradient: 'from-emerald-600 via-green-500 to-lime-400',
    pattern: 'url("data:image/svg+xml,%3Csvg width="60" height="60" viewBox="0 0 60 60" xmlns="http://www.w3.org/2000/svg"%3E%3Cg fill="none" fill-rule="evenodd"%3E%3Cg fill="%23059669" fill-opacity="0.05"%3E%3Cpath d="M36 34v-4h-2v4h-4v2h4v4h2v-4h4v-2h-4zm0-30V0h-2v4h-4v2h4v4h2V6h4V4h-4zM6 34v-4H4v4H0v2h4v4h2v-4h4v-2H6zM6 4V0H4v4H0v2h4v4h2V6h4V4H6z"/%3E%3C/g%3E%3C/g%3E%3C/svg%3E")',
    borderRadius: '1rem',
    shadow: '0 25px 50px -12px rgba(5, 150, 105, 0.3)',
  },
  {
    id: 'nature-desert',
    name: 'Пустынная',
    nameEn: 'Desert',
    primaryColor: '#D97706',
    secondaryColor: '#DC2626',
    accentColor: '#FBBF24',
    backgroundColor: '#1C1917',
    surfaceColor: '#292524',
    textColor: '#FEF3C7',
    textMuted: '#FCD34D',
    fontFamily: 'Inter, system-ui, sans-serif',
    headingFont: 'Playfair Display, serif',
    gradient: 'from-amber-600 via-orange-500 to-red-500',
    borderRadius: '0.5rem',
    shadow: '0 25px 50px -12px rgba(217, 119, 6, 0.3)',
  },
  // Минималистичные
  {
    id: 'minimal-white',
    name: 'Минимализм (белая)',
    nameEn: 'Minimal White',
    primaryColor: '#000000',
    secondaryColor: '#525252',
    accentColor: '#3B82F6',
    backgroundColor: '#FFFFFF',
    surfaceColor: '#F5F5F5',
    textColor: '#171717',
    textMuted: '#737373',
    fontFamily: 'Inter, system-ui, sans-serif',
    headingFont: 'Inter, system-ui, sans-serif',
    borderRadius: '0.5rem',
    shadow: '0 4px 6px -1px rgba(0, 0, 0, 0.1)',
  },
  {
    id: 'minimal-black',
    name: 'Минимализм (чёрная)',
    nameEn: 'Minimal Black',
    primaryColor: '#FFFFFF',
    secondaryColor: '#A3A3A3',
    accentColor: '#F97316',
    backgroundColor: '#0A0A0A',
    surfaceColor: '#171717',
    textColor: '#FAFAFA',
    textMuted: '#A3A3A3',
    fontFamily: 'Inter, system-ui, sans-serif',
    headingFont: 'Inter, system-ui, sans-serif',
    borderRadius: '0.5rem',
    shadow: '0 4px 6px -1px rgba(0, 0, 0, 0.5)',
  },
  // Неон и киберпанк
  {
    id: 'neon-cyber',
    name: 'Киберпанк',
    nameEn: 'Cyberpunk',
    primaryColor: '#FF00FF',
    secondaryColor: '#00FFFF',
    accentColor: '#FFFF00',
    backgroundColor: '#0D0D1A',
    surfaceColor: '#1A1A2E',
    textColor: '#FFFFFF',
    textMuted: '#B8B8D1',
    fontFamily: 'Rajdhani, sans-serif',
    headingFont: 'Orbitron, sans-serif',
    gradient: 'from-fuchsia-500 via-purple-500 to-cyan-500',
    borderRadius: '0.25rem',
    shadow: '0 0 30px rgba(255, 0, 255, 0.5), 0 0 60px rgba(0, 255, 255, 0.3)',
  },
  {
    id: 'neon-synthwave',
    name: 'Синтвейв',
    nameEn: 'Synthwave',
    primaryColor: '#FF6B9D',
    secondaryColor: '#C67DFF',
    accentColor: '#FFD93D',
    backgroundColor: '#1A0A2E',
    surfaceColor: '#2D1B4E',
    textColor: '#FFE5F1',
    textMuted: '#B794D6',
    fontFamily: 'Outfit, sans-serif',
    headingFont: 'Audiowide, sans-serif',
    gradient: 'from-pink-500 via-purple-500 to-indigo-500',
    borderRadius: '0rem',
    shadow: '0 0 40px rgba(255, 107, 157, 0.4)',
  },
  // Корпоративные
  {
    id: 'corporate-blue',
    name: 'Корпоративная (синяя)',
    nameEn: 'Corporate Blue',
    primaryColor: '#1E40AF',
    secondaryColor: '#3B82F6',
    accentColor: '#F59E0B',
    backgroundColor: '#FFFFFF',
    surfaceColor: '#EFF6FF',
    textColor: '#1E3A5F',
    textMuted: '#64748B',
    fontFamily: 'Source Sans Pro, sans-serif',
    headingFont: 'Source Sans Pro, sans-serif',
    borderRadius: '0.5rem',
    shadow: '0 10px 15px -3px rgba(30, 64, 175, 0.1)',
  },
  {
    id: 'corporate-green',
    name: 'Корпоративная (зелёная)',
    nameEn: 'Corporate Green',
    primaryColor: '#166534',
    secondaryColor: '#22C55E',
    accentColor: '#EAB308',
    backgroundColor: '#FFFFFF',
    surfaceColor: '#F0FDF4',
    textColor: '#14532D',
    textMuted: '#6B7280',
    fontFamily: 'Roboto, sans-serif',
    headingFont: 'Roboto, sans-serif',
    borderRadius: '0.75rem',
    shadow: '0 10px 15px -3px rgba(22, 101, 52, 0.1)',
  },
  // Креативные
  {
    id: 'creative-pastel',
    name: 'Пастельная',
    nameEn: 'Pastel',
    primaryColor: '#EC4899',
    secondaryColor: '#8B5CF6',
    accentColor: '#F472B6',
    backgroundColor: '#FDF2F8',
    surfaceColor: '#FFFFFF',
    textColor: '#831843',
    textMuted: '#9D174D',
    fontFamily: 'Nunito, sans-serif',
    headingFont: 'Quicksand, sans-serif',
    gradient: 'from-pink-300 via-purple-300 to-indigo-300',
    borderRadius: '2rem',
    shadow: '0 25px 50px -12px rgba(236, 72, 153, 0.2)',
  },
  {
    id: 'creative-bold',
    name: 'Яркая',
    nameEn: 'Bold',
    primaryColor: '#DC2626',
    secondaryColor: '#FBBF24',
    accentColor: '#22C55E',
    backgroundColor: '#18181B',
    surfaceColor: '#27272A',
    textColor: '#FAFAFA',
    textMuted: '#A1A1AA',
    fontFamily: 'Poppins, sans-serif',
    headingFont: 'Bebas Neue, sans-serif',
    borderRadius: '0rem',
    shadow: '0 25px 50px -12px rgba(220, 38, 38, 0.4)',
  },
  // Научные и академические
  {
    id: 'academic-classic',
    name: 'Академическая',
    nameEn: 'Academic',
    primaryColor: '#1E3A5F',
    secondaryColor: '#8B4513',
    accentColor: '#C4A35A',
    backgroundColor: '#FFFEF5',
    surfaceColor: '#FFF9E6',
    textColor: '#1A1A1A',
    textMuted: '#5C5C5C',
    fontFamily: 'Merriweather, serif',
    headingFont: 'Playfair Display, serif',
    borderRadius: '0.25rem',
    shadow: '0 4px 6px -1px rgba(0, 0, 0, 0.1)',
  },
  {
    id: 'science-lab',
    name: 'Научная лаборатория',
    nameEn: 'Science Lab',
    primaryColor: '#0891B2',
    secondaryColor: '#7C3AED',
    accentColor: '#10B981',
    backgroundColor: '#F0FDFA',
    surfaceColor: '#FFFFFF',
    textColor: '#134E4A',
    textMuted: '#5EEAD4',
    fontFamily: 'IBM Plex Sans, sans-serif',
    headingFont: 'IBM Plex Sans, sans-serif',
    gradient: 'from-cyan-500 to-purple-500',
    borderRadius: '1rem',
    shadow: '0 10px 15px -3px rgba(8, 145, 178, 0.2)',
  },
  // Ретро
  {
    id: 'retro-80s',
    name: 'Ретро 80-х',
    nameEn: 'Retro 80s',
    primaryColor: '#FF1493',
    secondaryColor: '#00CED1',
    accentColor: '#FFD700',
    backgroundColor: '#1A0533',
    surfaceColor: '#2D0A4E',
    textColor: '#FFFFFF',
    textMuted: '#E0B0FF',
    fontFamily: 'VT323, monospace',
    headingFont: 'Press Start 2P, cursive',
    gradient: 'from-pink-500 via-purple-500 to-cyan-400',
    borderRadius: '0rem',
    shadow: '0 0 30px rgba(255, 20, 147, 0.5)',
  },
  // Стеклянная
  {
    id: 'glass-morphism',
    name: 'Стеклянная',
    nameEn: 'Glass Morphism',
    primaryColor: '#FFFFFF',
    secondaryColor: '#E5E7EB',
    accentColor: '#6366F1',
    backgroundColor: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
    surfaceColor: 'rgba(255, 255, 255, 0.1)',
    textColor: '#FFFFFF',
    textMuted: 'rgba(255, 255, 255, 0.7)',
    fontFamily: 'Inter, system-ui, sans-serif',
    headingFont: 'Inter, system-ui, sans-serif',
    borderRadius: '1.5rem',
    shadow: '0 8px 32px 0 rgba(31, 38, 135, 0.37)',
  },
  // Золотая
  {
    id: 'luxury-gold',
    name: 'Золотая роскошь',
    nameEn: 'Luxury Gold',
    primaryColor: '#D4AF37',
    secondaryColor: '#C5A028',
    accentColor: '#FFD700',
    backgroundColor: '#0A0A0A',
    surfaceColor: '#1A1A1A',
    textColor: '#FFFFFF',
    textMuted: '#B8860B',
    fontFamily: 'Cormorant Garamond, serif',
    headingFont: 'Cinzel, serif',
    gradient: 'from-yellow-600 via-yellow-400 to-yellow-600',
    borderRadius: '0.25rem',
    shadow: '0 25px 50px -12px rgba(212, 175, 55, 0.3)',
  },
  // ==================== НОВЫЕ ТЕМЫ ====================
  // Космическая
  {
    id: 'space-galaxy',
    name: 'Космос',
    nameEn: 'Space Galaxy',
    primaryColor: '#8B5CF6',
    secondaryColor: '#6366F1',
    accentColor: '#F472B6',
    backgroundColor: '#0F0F1E',
    surfaceColor: '#1A1A2E',
    textColor: '#FFFFFF',
    textMuted: '#A5B4FC',
    fontFamily: 'Space Grotesk, sans-serif',
    headingFont: 'Orbitron, sans-serif',
    gradient: 'from-purple-900 via-indigo-800 to-blue-900',
    borderRadius: '1rem',
    shadow: '0 20px 40px rgba(139, 92, 246, 0.3)',
  },
  // Неоновый город
  {
    id: 'neon-city',
    name: 'Неоновый город',
    nameEn: 'Neon City',
    primaryColor: '#00F5FF',
    secondaryColor: '#FF00E5',
    accentColor: '#FFFF00',
    backgroundColor: '#0D0D1A',
    surfaceColor: '#1A1A2E',
    textColor: '#FFFFFF',
    textMuted: '#00F5FF',
    fontFamily: 'Rajdhani, sans-serif',
    headingFont: 'Audiowide, sans-serif',
    gradient: 'from-cyan-500 via-purple-500 to-pink-500',
    borderRadius: '0.5rem',
    shadow: '0 0 30px rgba(0, 245, 255, 0.5)',
  },
  // Японский минимализм
  {
    id: 'japanese-zen',
    name: 'Японский дзен',
    nameEn: 'Japanese Zen',
    primaryColor: '#C41E3A',
    secondaryColor: '#2D2D2D',
    accentColor: '#D4AF37',
    backgroundColor: '#FAFAFA',
    surfaceColor: '#FFFFFF',
    textColor: '#1A1A1A',
    textMuted: '#666666',
    fontFamily: 'Noto Sans JP, sans-serif',
    headingFont: 'Noto Serif JP, serif',
    gradient: 'from-red-100 via-white to-red-50',
    borderRadius: '0.25rem',
    shadow: '0 4px 20px rgba(0, 0, 0, 0.08)',
  },
  // Скандинавский
  {
    id: 'scandinavian',
    name: 'Скандинавский',
    nameEn: 'Scandinavian',
    primaryColor: '#2D4356',
    secondaryColor: '#435B66',
    accentColor: '#A76F6F',
    backgroundColor: '#FAF6F0',
    surfaceColor: '#FFFFFF',
    textColor: '#2D4356',
    textMuted: '#7F8C8D',
    fontFamily: 'Quicksand, sans-serif',
    headingFont: 'Poppins, sans-serif',
    gradient: 'from-slate-100 via-amber-50 to-slate-100',
    borderRadius: '0.75rem',
    shadow: '0 10px 30px rgba(45, 67, 86, 0.1)',
  },
  // Акварель
  {
    id: 'watercolor',
    name: 'Акварель',
    nameEn: 'Watercolor',
    primaryColor: '#6B9AC4',
    secondaryColor: '#97D8C4',
    accentColor: '#F4B9B2',
    backgroundColor: '#FFFDF9',
    surfaceColor: 'rgba(107, 154, 196, 0.1)',
    textColor: '#3D5A73',
    textMuted: '#7A9AB5',
    fontFamily: 'Caveat, cursive',
    headingFont: 'Playfair Display, serif',
    gradient: 'from-blue-100 via-green-50 to-pink-100',
    borderRadius: '2rem',
    shadow: '0 15px 40px rgba(107, 154, 196, 0.2)',
  },
  // Терракотовый
  {
    id: 'terracotta',
    name: 'Терракотовый',
    nameEn: 'Terracotta',
    primaryColor: '#C67B4E',
    secondaryColor: '#8B5A2B',
    accentColor: '#2F5233',
    backgroundColor: '#FAF5F0',
    surfaceColor: '#FFF8F0',
    textColor: '#3E2723',
    textMuted: '#8D6E63',
    fontFamily: 'DM Sans, sans-serif',
    headingFont: 'Fraunces, serif',
    gradient: 'from-orange-100 via-amber-50 to-orange-100',
    borderRadius: '1rem',
    shadow: '0 15px 35px rgba(198, 123, 78, 0.15)',
  },
  // Индустриальный
  {
    id: 'industrial',
    name: 'Индустриальный',
    nameEn: 'Industrial',
    primaryColor: '#CD7F32',
    secondaryColor: '#4A4A4A',
    accentColor: '#8B4513',
    backgroundColor: '#1C1C1C',
    surfaceColor: '#2D2D2D',
    textColor: '#E8E8E8',
    textMuted: '#9E9E9E',
    fontFamily: 'Roboto Mono, monospace',
    headingFont: 'Oswald, sans-serif',
    gradient: 'from-zinc-800 via-zinc-700 to-zinc-800',
    borderRadius: '0.25rem',
    shadow: '0 10px 40px rgba(205, 127, 50, 0.2)',
  },
  // Мятный
  {
    id: 'mint-fresh',
    name: 'Мятная свежесть',
    nameEn: 'Mint Fresh',
    primaryColor: '#00B894',
    secondaryColor: '#00CEC9',
    accentColor: '#FDCB6E',
    backgroundColor: '#F0FFF4',
    surfaceColor: '#FFFFFF',
    textColor: '#1A3A32',
    textMuted: '#6B8E81',
    fontFamily: 'Nunito, sans-serif',
    headingFont: 'Montserrat, sans-serif',
    gradient: 'from-emerald-100 via-teal-50 to-cyan-100',
    borderRadius: '1.25rem',
    shadow: '0 15px 40px rgba(0, 184, 148, 0.15)',
  },
  // Лавандовый
  {
    id: 'lavender-dream',
    name: 'Лавандовые мечты',
    nameEn: 'Lavender Dream',
    primaryColor: '#9B59B6',
    secondaryColor: '#8E44AD',
    accentColor: '#F1C40F',
    backgroundColor: '#F8F4FC',
    surfaceColor: '#FFFFFF',
    textColor: '#4A235A',
    textMuted: '#8E44AD',
    fontFamily: 'Lora, serif',
    headingFont: 'Cormorant Garamond, serif',
    gradient: 'from-purple-100 via-violet-50 to-fuchsia-100',
    borderRadius: '1.5rem',
    shadow: '0 20px 50px rgba(155, 89, 182, 0.15)',
  },
  // Бруталистский
  {
    id: 'brutalist',
    name: 'Бруталист',
    nameEn: 'Brutalist',
    primaryColor: '#000000',
    secondaryColor: '#333333',
    accentColor: '#FF0000',
    backgroundColor: '#FFFFFF',
    surfaceColor: '#F5F5F5',
    textColor: '#000000',
    textMuted: '#666666',
    fontFamily: 'Space Mono, monospace',
    headingFont: 'Anton, sans-serif',
    gradient: 'from-white to-gray-100',
    borderRadius: '0',
    shadow: '8px 8px 0px #000000',
  },
  // Карамель
  {
    id: 'caramel',
    name: 'Карамель',
    nameEn: 'Caramel',
    primaryColor: '#D2691E',
    secondaryColor: '#CD853F',
    accentColor: '#8B4513',
    backgroundColor: '#FFF8DC',
    surfaceColor: '#FFFAF0',
    textColor: '#4A3728',
    textMuted: '#8B7355',
    fontFamily: 'Merriweather, serif',
    headingFont: 'Abril Fatface, cursive',
    gradient: 'from-amber-100 via-orange-50 to-yellow-100',
    borderRadius: '1rem',
    shadow: '0 15px 40px rgba(210, 105, 30, 0.15)',
  },
  // Морской
  {
    id: 'ocean-deep',
    name: 'Глубокий океан',
    nameEn: 'Deep Ocean',
    primaryColor: '#006994',
    secondaryColor: '#004E6D',
    accentColor: '#00CED1',
    backgroundColor: '#001824',
    surfaceColor: '#002B3D',
    textColor: '#E8F4F8',
    textMuted: '#87CEEB',
    fontFamily: 'Source Sans Pro, sans-serif',
    headingFont: 'Bebas Neue, sans-serif',
    gradient: 'from-blue-900 via-cyan-800 to-teal-900',
    borderRadius: '0.75rem',
    shadow: '0 20px 50px rgba(0, 105, 148, 0.4)',
  },
  // Винтаж
  {
    id: 'vintage-paper',
    name: 'Винтажная бумага',
    nameEn: 'Vintage Paper',
    primaryColor: '#8B4513',
    secondaryColor: '#A0522D',
    accentColor: '#CD853F',
    backgroundColor: '#F5E6D3',
    surfaceColor: '#FDF5E6',
    textColor: '#3E2723',
    textMuted: '#795548',
    fontFamily: 'EB Garamond, serif',
    headingFont: 'Playfair Display SC, serif',
    gradient: 'from-amber-100 via-orange-50 to-yellow-50',
    borderRadius: '0.5rem',
    shadow: '0 10px 30px rgba(139, 69, 19, 0.15)',
  },
  // Арктика
  {
    id: 'arctic-frost',
    name: 'Арктический лёд',
    nameEn: 'Arctic Frost',
    primaryColor: '#7DD3FC',
    secondaryColor: '#BAE6FD',
    accentColor: '#0EA5E9',
    backgroundColor: '#F0F9FF',
    surfaceColor: '#FFFFFF',
    textColor: '#0C4A6E',
    textMuted: '#0369A1',
    fontFamily: 'Inter, sans-serif',
    headingFont: 'Exo 2, sans-serif',
    gradient: 'from-sky-100 via-blue-50 to-cyan-100',
    borderRadius: '1rem',
    shadow: '0 15px 40px rgba(14, 165, 233, 0.12)',
  },
  // Вампирский
  {
    id: 'vampire-night',
    name: 'Вампирская ночь',
    nameEn: 'Vampire Night',
    primaryColor: '#8B0000',
    secondaryColor: '#4A0000',
    accentColor: '#DC143C',
    backgroundColor: '#0A0A0A',
    surfaceColor: '#1A0A0A',
    textColor: '#F5F5F5',
    textMuted: '#8B0000',
    fontFamily: 'Crimson Text, serif',
    headingFont: 'Nosifer, cursive',
    gradient: 'from-red-950 via-black to-red-950',
    borderRadius: '0.25rem',
    shadow: '0 20px 50px rgba(139, 0, 0, 0.5)',
  },
  // Конфетти
  {
    id: 'confetti-party',
    name: 'Конфетти',
    nameEn: 'Confetti Party',
    primaryColor: '#FF6B6B',
    secondaryColor: '#4ECDC4',
    accentColor: '#FFE66D',
    backgroundColor: '#FFFFFF',
    surfaceColor: '#FFF9F9',
    textColor: '#2C3E50',
    textMuted: '#7F8C8D',
    fontFamily: 'Comfortaa, cursive',
    headingFont: 'Baloo 2, cursive',
    gradient: 'from-pink-100 via-yellow-100 to-cyan-100',
    borderRadius: '2rem',
    shadow: '0 15px 40px rgba(255, 107, 107, 0.2)',
  },
  // Изумрудный
  {
    id: 'emerald-luxury',
    name: 'Изумрудная роскошь',
    nameEn: 'Emerald Luxury',
    primaryColor: '#047857',
    secondaryColor: '#065F46',
    accentColor: '#D4AF37',
    backgroundColor: '#022C22',
    surfaceColor: '#064E3B',
    textColor: '#ECFDF5',
    textMuted: '#6EE7B7',
    fontFamily: 'Libre Baskerville, serif',
    headingFont: 'Cinzel Decorative, cursive',
    gradient: 'from-emerald-900 via-green-800 to-teal-900',
    borderRadius: '0.5rem',
    shadow: '0 25px 50px rgba(4, 120, 87, 0.4)',
  },
];

